config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :submissions, only: %i[edit update show] do
    member do
      get :review # Edit review
      post :submit
      get :reader_review
      get :preview # Signature page preview
      patch :attach_supplemental_files
      patch :attach_permission_files
      get :supplemental_files
      get 'permission_files/:file_id', to: 'submissions#permission_file', as: :permission_file
      get 'supplemental_files/:file_id', to: 'submissions#supplemental_file', as: :supplemental_file
      get :dissertation_file
      get :augmented_dissertation_file
    end
  end

  resources :supplemental_files, only: %i[update]
  resources :permission_files, only: %i[update]
  resources :etds, only: %i[index create]

  get 'view/:id', to: redirect('/submissions/%{id}/reader_review'), as: :legacy_view_show
  get 'submit/:id', to: redirect('/submissions/%{id}'), as: :legacy_submit_show
  get 'submit/:id/edit', to: redirect('/submissions/%{id}/edit'), as: :legacy_submit_edit

  mount MissionControl::Jobs::Engine, at: '/jobs'
  ActiveAdmin.routes(self)
end

app/models/submission.rb
# frozen_string_literal: true

# Model for submissions.
class Submission < ApplicationRecord
  include PersonNameConcern
  include SubmissionAdminConcern

  DOI_SERVICE_ENABLED_DATE = Date.parse('2025-09-18').freeze

  # Fields transferred from PeopleSoft
  # - dissertation_id
  # - title
  # - etd_type (from type field)
  # - ps_career (from career)
  # - department (from program)
  # - degree
  # - major (from plan)
  # - degree
  # - ps_subplan
  # - provost (from vpname)
  # - name
  # - sub
  # - readerapproval
  # - readercomment
  # - readeractiondttm
  # - regapproval
  # - regcomment
  # - regactiondttm
  # - documentaccess
  # - univid
  # - sunetid
  # - degreeconfyr
  # - schoolname

  # Values provided by student
  # - abstract
  # - containscopyright (boolean; used in Hydra but not Heracles)
  # - sulicense (boolean for checkbox; currently has "true" or nil)
  # - cclicense (creative commons license)
  # - embargo

  # Derivative fields (set in Submission based on other fields)
  # - cclicensetype (set from cclicense)
  # - submitted_to_registrar (boolean; set if submitted_at present)

  # UI section flags (boolean)
  # - citation_verified
  # - abstract_provided
  # - dissertation_uploaded
  # - supplemental_files_uploaded
  # - permission_files_uploaded
  # - rights_selected
  # - format_reviewed

  # Other UI flags (boolean)
  # - permissions_provided (toggle indicating that permission files will be provided)
  # - supplemental_files_provided (toggle indicating that supplemental files will be provided)

  # Dates
  # - submitted_at (set by SubmissionPoster service)
  # - last_registrar_action_at
  # - last_reader_action_at
  # - ils_record_created_at (set by CreateStubMarcRecordJob)
  # - ils_record_updated_at (unclear; previously set by CatalogStatusJob)
  # - accessioning_started_at (set by StartAccessionJob)

  # Other
  # - folio_instance_hrid (set by CreateStubMarcRecordJob)
  # - orcid (set by SubmissionsController)

  before_save :set_derivative_fields

  has_many :readers, -> { order(position: :asc) }, dependent: :destroy, inverse_of: :submission

  # Active Storage attachments
  has_one_attached :dissertation_file, dependent: :purge_later
  has_one_attached :augmented_dissertation_file, dependent: :purge_later

  has_many :supplemental_files, dependent: :destroy, inverse_of: :submission
  accepts_nested_attributes_for :supplemental_files, allow_destroy: true

  has_many :permission_files, dependent: :destroy, inverse_of: :submission
  accepts_nested_attributes_for :permission_files, allow_destroy: true

  validates :dissertation_id, presence: true
  validates :druid, presence: true
  validates :etd_type, presence: true, inclusion: { in: %w[Thesis Dissertation] }
  validates :sunetid, presence: true
  validates :title, presence: true
  validates :embargo, inclusion: { in: ['1 year', '2 years', 'immediately', '6 months'], allow_blank: true }

  # This scope checks for ETDs that have been sent to the ILS since yesterday at 6am and have not yet been updated.
  # It is used to by a cron job to send reminder emails to the catalogers
  scope :ils_records_created_since_yesterday_morning, -> {
    at_ils_loaded.where('ils_record_created_at > ?', Time.now.yesterday.change(hour: 6).utc)
  }

  # Defining `#to_param` this makes the diss ID the default param to use when
  # building a path or URL for a submission. E.g., `submission_path(submission)`
  # will now route to `/submissions/000001234` (the diss ID) instead of
  # `/submissions/357` (the DB ID).
  def to_param
    dissertation_id
  end

  def to_honeybadger_context
    {
      dissertation_id:,
      sunetid:,
      druid:
    }
  end

  # These are the values needed to send to PeopleSoft when submitting a submission.
  def to_peoplesoft_hash
    {
      dissertation_id:,
      title:,
      type: etd_type,
      timestamp: submitted_at,
      purl:
    }
  end

  def copyright_statement
    "© #{submitted_at&.year || Time.zone.today.year} by #{first_last_name}. All rights reserved."
  end

  def doi
    # On 2025-09-18, the ETD application began registering DOIs for every
    # submission, and we want to display the DOI so users have a record before
    # it is minted. Any submissions created before that date should be
    # considered not to have DOIs. We also guard against returning a DOI for
    # in-memory submissions, which do not yet have a created_at value to compare
    # against, as this can occur in the test suite.
    return if created_at.blank? || created_at < DOI_SERVICE_ENABLED_DATE

    "#{Settings.datacite.prefix}/#{druid.delete_prefix('druid:')}"
  end

  def purl
    "#{Settings.purl.url}/#{druid.delete_prefix('druid:')}"
  end

  def thesis?
    etd_type == 'Thesis'
  end

  def submitted?
    submitted_at.present?
  end

  def ready_for_cataloging?
    /approved/i.match?(regapproval) && /approved/i.match?(readerapproval)
  end

  def creative_commons_license
    CreativeCommonsLicense.find(cclicense)
  end

  def embargo_release_date
    return if embargo.blank?

    Embargo.embargo_date(start_date: last_registrar_action_at, id: embargo)
  end

  def set_derivative_fields
    self.submitted_to_registrar = submitted_at.present? ? 'true' : 'false'
    self.cclicensetype = CreativeCommonsLicense.find(cclicense)&.name
  end

  def prepare_to_submit!
    Submission.transaction do
      update!(submitted_at: Time.zone.now, readerapproval: nil, last_reader_action_at: nil,
              readercomment: nil, regapproval: nil, last_registrar_action_at: nil, regcomment: nil)
      generate_and_attach_augmented_file!(raise_if_dissertation_missing: true)

      # If the submission to the Registrar fails, we want to roll back the changes
      # above so the submission doesn't get in a state where it shows as having
      # been submitted when it hasn't been submitted.
      yield if block_given?
    end
  end

  def generate_and_attach_augmented_file!(raise_if_dissertation_missing: false)
    augmented_pdf_path = SignaturePageService.call(submission: self)
    augmented_dissertation_file.attach(
      io: File.open(augmented_pdf_path),
      filename: augmented_pdf_filename
    )
    File.delete(augmented_pdf_path)
  rescue TypeError => e
    # Student has not yet uploaded their dissertation file.
    raise e if raise_if_dissertation_missing
  end

  def augmented_pdf_filename
    dissertation_file
      .filename
      .to_s
      .sub(/\.pdf$/, '-augmented.pdf')
  end
end

app/controllers/submissions_controller.rb
# frozen_string_literal: true

# Controller for Submissions
class SubmissionsController < ApplicationController
  before_action :set_submission
  before_action :authorize_submission, except: [:edit]

  def show
    # PeopleSoft sends all users to the show route, but if this is the student
    # and the submission hasn't been submitted yet, they should see the edit
    # view.
    redirect_to edit_submission_path(@submission) if allowed_to?(:update?, @submission) && !@submission.submitted?
  end

  def edit
    if @submission.submitted?
      # Allow the redirect to happen, and let the `show` action do its own authorization
      skip_verify_authorized!
      return redirect_to submission_path(@submission)
    end

    authorize! @submission # Authorization has to happen after the redirect check

    # The current user's orcid is provided via shibboleth. It needs to be added
    # to the submission via the edit view.
    @submission.update!(orcid: current_user.orcid) if needs_orcid_update?
  end

  def update # rubocop:disable Metrics/AbcSize, Metrics/MethodLength
    # All validation happens client-side, so not validating here.
    if params.dig(:submission, :remove_dissertation_file)
      @submission.dissertation_file.purge
    elsif params.dig(:submission, :remove_supplemental_file)
      @submission.supplemental_files.find(params[:submission][:remove_supplemental_file]).delete
    elsif params.dig(:submission, :remove_permission_file)
      @submission.permission_files.find(params[:submission][:remove_permission_file]).delete
    else
      @submission.update!(submission_params)
      # NOTE: This is, we hope, a temporary alert to check whether a Feb. 2026 patch
      #       fixed a bug that cropped up in Oct. 2025 allowing users to submit
      #       ETDs with blank abstracts.
      if @submission.abstract_provided && @submission.abstract.blank?
        Honeybadger.notify(
          '[WARNING] User has collapsed the abstract section with blank abstract! (Check logs & alert service manager)',
          context: {
            submission: @submission,
            params: params
          }
        )
      end
      if @submission.dissertation_file.attached?
        @submission.generate_and_attach_augmented_file!(raise_if_dissertation_missing: true)
      end
    end
    redirect_to edit_submission_path(@submission)
  end

  def review; end

  def submit
    # NOTE: If the following line proves too slow in UAT/prod, use this job-based approach:
    #       PostSubmissionJob.perform_later(submission: @submission)
    SubmissionPoster.call(submission: @submission)
    redirect_to submission_path(@submission)
  end

  def reader_review; end

  def preview
    send_file SignaturePagePreviewService.call(submission: @submission), filename: 'preview.pdf',
                                                                         type: 'application/pdf', disposition: 'inline'
  end

  def attach_supplemental_files
    supplemental_files = supplemental_file_params.fetch(:supplemental_files, [])
    return if supplemental_files.empty?

    supplemental_files.each do |file|
      next if file.blank?

      supplemental_file = SupplementalFile.new(submission: @submission)
      supplemental_file.file.attach(file)
      supplemental_file.save!
    end
    redirect_to edit_submission_path(@submission)
  end

  def attach_permission_files
    permission_files = permission_file_params.fetch(:permission_files, [])
    return if permission_files.empty?

    permission_files.each do |file|
      next if file.blank?

      permission_file = PermissionFile.new(submission: @submission)
      permission_file.file.attach(file)
      permission_file.save!
    end
    redirect_to edit_submission_path(@submission)
  end

  def dissertation_file
    return head :not_found unless @submission.dissertation_file.attached?

    send_file ActiveStorageSupport.filepath_for_blob(@submission.dissertation_file),
              type: @submission.dissertation_file.content_type,
              filename: @submission.dissertation_file.filename.to_s,
              disposition: 'attachment'
  end

  # Use the original filename when downloading the augmented file
  def augmented_dissertation_file
    return head :not_found unless @submission.augmented_dissertation_file.attached?

    send_file ActiveStorageSupport.filepath_for_blob(@submission.augmented_dissertation_file),
              type: @submission.augmented_dissertation_file.content_type,
              filename: @submission.dissertation_file.filename.to_s,
              disposition: 'attachment'
  end

  def permission_file
    permission_file = @submission.permission_files.find(params[:file_id])
    send_file ActiveStorageSupport.filepath_for_blob(permission_file.file),
              type: permission_file.content_type,
              filename: permission_file.filename.to_s,
              disposition: 'attachment'
  end

  def supplemental_file
    supplemental_file = @submission.supplemental_files.find(params[:file_id])
    send_file ActiveStorageSupport.filepath_for_blob(supplemental_file.file),
              type: supplemental_file.content_type,
              filename: supplemental_file.filename.to_s,
              disposition: 'attachment'
  end

  private

  def needs_orcid_update?
    return false if @submission.orcid.present?
    return false if current_user.orcid.blank?
    # Note that the sunetid check is redundant given the submission policy, but
    # we are explicit here just in case the policy is changed in the future.
    return false if @submission.sunetid != current_user.sunetid

    true
  end

  # NOTE: The submissions controller allows users to supply either the
  #       dissertation ID *or* the druid to find the correct submission. This is
  #       used often by the service manager.
  def set_submission
    @submission = if params[:id]&.start_with?('druid:')
                    Submission.find_by!(druid: params[:id])
                  else
                    Submission.find_by!(dissertation_id: params[:id])
                  end
  end

  def authorize_submission
    authorize! @submission
  end

  def submission_params
    params.expect(submission: [:abstract, :sulicense, :cclicense, :embargo, :citation_verified,
                               :format_reviewed, :abstract_provided, :rights_selected, :dissertation_file,
                               :dissertation_uploaded, { supplemental_files: [] }, :supplemental_files_uploaded,
                               { permission_files: [] }, :permission_files_uploaded, :permissions_provided,
                               :supplemental_files_provided])
  end

  def permission_file_params
    params.expect(submission: [{ permission_files: [] }])
  end

  def supplemental_file_params
    params.expect(submission: [{ supplemental_files: [] }])
  end
end

app/views/submissions/edit.html.erb
<% content_for :title, 'Submit your dissertation or thesis' %>
<% content_for :head do %>
  <meta name="turbo-refresh-method" content="morph">
  <meta name="turbo-refresh-scroll" content="preserve">
<% end %>

<% content_for :header do %>
  <%= render HeaderComponent.new(current_user: @current_user,
                                 title: t('submitter.title'),
                                 subtitle: t('submitter.subtitle')) %>
<% end %>

<div class="container">
  <div class="row gy-2" data-controller="focus" data-action="turbo:render@window->focus#restoreFocus">
    <div id="focus" data-turbo-permanent="true" data-focus-target="permanent"></div>
    <div class="col-lg-8 order-2 order-lg-1">
      <%= render Edit::WelcomeBannerComponent.new(submission: @submission) %>

      <%= render Edit::CitationStepComponent.new(submission: @submission) %>
      <%= render Edit::AbstractStepComponent.new(submission: @submission) %>
      <%= render Edit::FormatStepComponent.new(submission: @submission) %>
      <%= render Edit::DissertationStepComponent.new(submission: @submission) %>
      <%= render Edit::SupplementalFilesStepComponent.new(submission: @submission) %>
      <%= render Edit::PermissionFilesStepComponent.new(submission: @submission) %>
      <%= render Edit::RightsStepComponent.new(submission: @submission) %>
      <%= render Edit::SubmittedStepComponent.new(submission: @submission) %>
    </div>
    <div class="col-lg-3 order-1 order-lg-2">
      <%= render Shared::ProgressCardComponent.new(submission: @submission) %>
    </div>
  </div>
</div>

app/views/submissions/reader_review.html.erb
<% content_for :title, 'View dissertation or thesis' %>
<% content_for :header do %>
  <%= render HeaderComponent.new(current_user: @current_user,
                                 title: 'View dissertation or thesis',
                                 subtitle: 'Reader review and approval') %>
<% end %>

<div class="container">
  <div class="row gy-2">
    <div class="col-lg-8 order-2 order-lg-1">
      <%= render Elements::StatusAlertComponent.new do %>
        <div><span class="fw-bold">Dissertation ID:</span> <%= @submission.dissertation_id %></div>
        <div><%= render Elements::ExternalLinkComponent.new(url: 'https://inside-studentservices.stanford.edu/supporting-students-across-topics/academic-progress-graduation/degree-progress-graduate-0', label: 'Faculty guide for reviewing theses and dissertations') %></div>
      <% end %>

      <%= render ReaderReview::CitationStepComponent.new(submission: @submission) %>
      <%= render ReaderReview::AbstractStepComponent.new(submission: @submission) %>
      <%= render ReaderReview::RightsStepComponent.new(submission: @submission) %>
      <%= render ReaderReview::DissertationComponent.new(submission: @submission) %>
      <%= render ReaderReview::SupplementalFilesComponent.new(submission: @submission) %>
      <%= render ReaderReview::PermissionFilesComponent.new(submission: @submission) %>
    </div>
    <div class="col-lg-3 order-1 order-lg-2">
      <%= render Shared::ProgressCardComponent.new(submission: @submission, with_student_steps: false) %>
    </div>
  </div>
</div>

app/views/submissions/review.html.erb
<% content_for :title, 'Review your dissertation or thesis' %>
<% content_for :header do %>
  <%= render HeaderComponent.new(current_user: @current_user,
                                 title: t('submitter.title'),
                                 subtitle: t('submitter.subtitle')) %>
<% end %>

<div class="container without-progress-bar">
  <%= render Elements::ButtonLinkComponent.new(variant: :link, link: edit_submission_path(@submission), classes: 'mb-3') do %>
    <i class="bi bi-arrow-left me-1"></i> Go back and make changes
  <% end %>

  <div class="h3">Review and submit</div>
  <div class="h5 mb-4">Scroll down to review your details and selections before submitting.</div>

  <%= render Elements::StatusAlertComponent.new(variant: :warning) do %>
    After your thesis or dissertation has been submitted to the Registrar, no further changes can be made.
  <% end %>

  <%= render Show::CitationStepComponent.new(submission: @submission) %>
  <%= render Show::AbstractStepComponent.new(submission: @submission) %>
  <%= render Show::FormatStepComponent.new(submission: @submission) %>
  <%= render Show::DissertationStepComponent.new(submission: @submission) %>
  <%= render Show::SupplementalFilesStepComponent.new(submission: @submission) %>
  <%= render Show::PermissionFilesStepComponent.new(submission: @submission) %>
  <%= render Show::RightsStepComponent.new(submission: @submission) %>

  <div class="d-flex align-items-baseline w-100">
    <div class="me-auto">By clicking Submit, I verify my thesis or dissertation is complete.</div>
    <div>
      <%= render Elements::ButtonLinkComponent.new(label: 'Go back', variant: :'outline-primary', link: submit_submission_path(@submission), classes: 'me-3') %>
    </div>
    <div>
      <%= form_with model: @submission, url: submit_submission_path(@submission), method: :post do |form| %>
        <%= form.submit 'Submit to Registrar', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/submissions/show.html.erb
<% content_for :title, 'View your dissertation or thesis' %>
<% content_for :header do %>
  <%= render HeaderComponent.new(current_user: @current_user,
                                 title: t('submitter.title'),
                                 subtitle: t('submitter.subtitle')) %>
<% end %>

<div class="container">
  <div class="row gy-2">
    <div class="col-lg-8 order-2 order-lg-1">
      <% unless @current_user.sunetid == @submission.sunetid %>
        <%= render Elements::StatusAlertComponent.new(title: 'Read-only administrative view', variant: :warning) do %>
          This is a read-only view of the student's ETD submission.
        <% end %>
      <% end %>

      <%= render Show::WelcomeBannerComponent.new(submission: @submission) %>
      <%= render Show::CitationStepComponent.new(submission: @submission) %>
      <%= render Show::AbstractStepComponent.new(submission: @submission) %>
      <%= render Show::FormatStepComponent.new(submission: @submission) %>
      <%= render Show::DissertationStepComponent.new(submission: @submission) %>
      <%= render Show::SupplementalFilesStepComponent.new(submission: @submission) %>
      <%= render Show::PermissionFilesStepComponent.new(submission: @submission) %>
      <%= render Show::RightsStepComponent.new(submission: @submission) %>
      <%= render Show::SubmittedStepComponent.new(submission: @submission) %>
    </div>
    <div class="col-lg-3 order-1 order-lg-2">
      <%= render Shared::ProgressCardComponent.new(submission: @submission) %>
    </div>
  </div>
</div>

app/views/submissions/submit.xml.erb
<?xml version="1.0"?>
<dissertation>
  <dissertationid><%= dissertation_id %></dissertationid>
  <title><%= CGI.escapeHTML(title) %></title>
  <type><%= type %></type>
  <status code="SB">submit</status>
  <actiondttm><%= timestamp.strftime('%m/%d/%Y %H:%M:%S') %></actiondttm>
  <purl><%= purl %></purl>
</dissertation>